CraftLayout/CraftLayout/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('services.urls')),
    path('', include('users.urls')),
    path('', include('exchange.urls')),
    path('', include('massanger.urls')),
]
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

CraftLayout/exchange/urls.py
from django.db import router
from django.urls import path
from . import views as exchViews
urlpatterns = [
    path('exchange/', exchViews.exchangePage, name='exchange'),
    path('exchange/<int:id>', exchViews.OrderPage),
    path('createOrder/', exchViews.DoOrderPage, name='createOrder'),
]

CraftLayout/users/urls.py
from telnetlib import LOGOUT
from django.contrib import admin
from django.urls import path
from django.conf import settings
from django.contrib.auth import views as authViews
from .views import profile, RegisterPage, AvatarPage, BannerPage, ChangeProfPage
urlpatterns = [
    path('changeBanner/', BannerPage, name="changeBanner"),
    path('changeProfile/', ChangeProfPage, name="changeProfile"),
    path('changeAvatar/', AvatarPage, name="changeAvatar"),
    path('reg/', RegisterPage, name='reg'),
    path('profile/<str:slugFil>', profile, name='profile'),
    path('login/', authViews.LoginView.as_view(template_name='users/login.html'), name='login'),
    path('exit/', authViews.LogoutView.as_view(template_name='users/exit.html'), name='exit')
]

CraftLayout/exchange/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils import timezone



class Exchange(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    title = models.CharField(max_length=255)
    salary = models.CharField(default='Agreements' ,max_length=255)
    text = models.TextField()
    technologies = models.CharField(max_length=255, default=' ')
    date = models.DateField(default=timezone.now)
    id = models.AutoField(primary_key=True)

    def __str__(self):
        return f'Order {self.user} at {self.date}'

CraftLayout/exchange/forms.py
from django import forms
from django.forms import ModelForm
from dataclasses import fields
from pyexpat import model
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm
from .models import Exchange

class FormExchange(ModelForm):
    title = forms.CharField(required=True)
    salary = forms.CharField(required=True)
    text = forms.Textarea()
    technologies = forms.CharField(required=True)
    class Meta:
        model = Exchange
        fields = ['title','salary','text', 'technologies', 'id']

CraftLayout/exchange/views.py
from django.shortcuts import render, redirect
from .models import Exchange
from .forms import FormExchange
def exchangePage(request):
    orders = Exchange.objects.all()
    context = {'data': orders}
    return render(request, 'exchange/exchange.html', context)

def OrderPage(request, id):
    orders = Exchange.objects.filter(pk=id)
    context = {'data': orders}
    return render(request, 'exchange/exchangeOrder.html', context)

def DoOrderPage(request):
    if request.method == "POST":
        form = FormExchange(request.POST)
        if form.is_valid():
            order = form.save(commit=False)
            order.user = request.user
            order.save()
            
            return redirect('/exchange/' + str(order.id) )
    else:
        form = FormExchange()
    return render(request, 'exchange/createExchange.html', {'form': form})

CraftLayout/exchange/templates/exchange/createExchange.html
{% extends 'services/main-layout.html' %}
{% block Title %}Create Exchange{% endblock %}

{% block content%}
    <div style='height:800px;' class='container d-flex justify-content-center align-items-center'>
        {% if user.is_authenticated%}
        <form class="registerform FormExch" method="post">
            {% csrf_token %}
            <label id='id_title'>Title</label>
            {{ form.title }}
            <label id='id_salary'>Salary</label>
            {{ form.salary }}
            <placeholder>Text</placeholder>
            {{ form.text }}<br> 
            <div class="pt-4"></div>
            <label class="" id='id_technologies'>Technologies</label>
            {{ form.technologies }}
            <p class='PozorMess'>You must write technologies through ',' example 'Php,Django,Python,Cms'</p>
            <button class="btn my-2 flare-button">Create Order</button>
        </form>
        {% else%}
        <p class='PozorMess'>User is not authenticated. Please <a href={% url 'reg'%}>register</a>, or <a href={% url 'login'%}>login</a> in your account</p>
        {% endif%}
    </div>
{% endblock%}

{% block scripts%}  
<script>
    let labels = document.querySelectorAll('label')
    let inputs = document.querySelectorAll('input')
    for(var i = 1; i > inputs.length; i++){
        inputs[i].val() = ''
    }
    $('input').focus(function(){
        for(var elem in labels){
            if($(this).attr("id") == labels[elem].id){
                labels[elem].classList.add('ACTIVElab')
            }

        }
    });

    $('input').focusout(function(){
        for(var elem in labels){
            if($(this).attr("id") == labels[elem].id){
                labels[elem].classList.remove('ACTIVElab')
                if($(this).val() != ''){
                    labels[elem].classList.add('ACTIVElab')
                }
            }
        }
    });
</script>
{% endblock%}

CraftLayout/exchange/templates/exchange/exchange.html
{% extends 'services/main-layout.html' %}
{% block Title %}Exchange{% endblock %}
{% block content%}
<div style="min-height: 640px;" class='container'>
    <div class="mt-2 row">
        <div class="col-2">
            <div class="my-4">
                <h2>Filters</h2>
                <input class="inputCheckTehc" type="checkbox" value="Php">Php</input></br>
                <input class="inputCheckTehc" type="checkbox" value="Django">Django</input></br>
                <input class="inputCheckTehc" type="checkbox" value="Python">Python</input></br>
                <input class="inputCheckTehc" type="checkbox" value="React.js">React.js</input></br>
                <input class="inputCheckTehc" type="checkbox" value="Angular.js">Angular.js</input></br>
                <input class="inputCheckTehc" type="checkbox" value="Rust">Rust</input></br>
                <input class="inputCheckTehc" type="checkbox" value="C++">C++</input></br>
                <input class="inputCheckTehc" type="checkbox" value="C#">C#</input></br>
                <input class="inputCheckTehc" type="checkbox" value="C">C</input></br>
                <input class="inputCheckTehc" type="checkbox" value="Next.js">Next.js</input></br>
                <input class="inputCheckTehc" type="checkbox" value="Vue.js">Vue.js</input></br>
                <input class="inputCheckTehc" type="checkbox" value="Cms">Cms</input></br>
                <button class="btn my-2 flare-button">Use filters</button>
            </div>
        </div>
        <div class="col-10">
            {% for order in data%}
            <div class='orderExchange my-4 p-4 text-light'>
                <div class="d-flex pb-3 align-items-center">
                    <a href={% url 'profile' slugFil=order.user %}>
                        <img class="hoverLinkExch" style="width: 80px; height: 80px; border-radius: 50%;" src={{ order.user.profile.Avatar.url}}>
                    </a>
                    <div class="ms-3">
                        <div class="h4">{{ order.title}}</div>
                        <div class="">{{ order.salary}}</div>
                    </div>
                </div>
                <p class="techExchange">Technologies: <em class="">{{ order.technologies}}</em></p>
                <div class="">{{ order.text|truncatechars:250}}</div>
                <a href={{ order.id }}><button class="btnExchange text-uppercase my-2 px-5">See more</button></a>
                <div class="d-flex justify-content-between pt-2">
                    <div class="d-flex">
                        <div class="text-uppercase">{{ order.user|truncatechars:25}}</div>
                        <em class="ps-3" style="opacity: .7;">{{ order.user.profile.position|truncatechars:25}}</em>
                    </div>
                    <div class="text-uppercase"></div>
                    <div class="">{{ order.date}}</div>
                </div>
            </div>
            {% endfor%}
        </div>  
    </div>

</div>
{% endblock%}
{% block scripts%}  
<script>
    orderExchange = document.querySelectorAll('.orderExchange .techExchange em')

    for(let i = 0; i< orderExchange.length; i++){
        orderExchange[i].innerHTML = orderExchange[i].innerHTML.replace( /\s/g, "")
    }

    $('.inputCheckTehc').click(function(){
        for(let i = 0; i < orderExchange.length; i++){
            orderExchange[i].parentNode.parentNode.style.display = 'block'
        }
    })


    $('.inputCheckTehc ~ button').on('click', function(){
        let inputCheck = document.querySelectorAll('.inputCheckTehc')
        let ar = new Array()
        for(let i = 0; i < inputCheck.length; i++){
            if (inputCheck[i].checked == true){
                ar.push(inputCheck[i].value)
            }
        }
        for(let i = 0; i < orderExchange.length; i++){
            let b = orderExchange[i].innerHTML.split(',')
            for(let j = 0; j < b.length; j++){
                let show = true
                if(ar.length == 0){
                    orderExchange[i].parentNode.parentNode.style.display = 'block'
                    break
                }
                for(let g = 0; g < ar.length; g++){
                    if(ar[g] == b[j]){
                        show = true
                    }
                    else{
                        show = false
                    }
                    if(show == true){
                        break
                    }
                    else if(b[b.length - 1] != b[j] && show == false){
                        break
                    }
                    else if(b[b.length - 1] == b[j] && show == false){
                        orderExchange[i].parentNode.parentNode.style.display = 'none'
                    }
                }
                if(show == true){
                    break
                }
            }
        }
    });
</script>
{% endblock%}

CraftLayout/exchange/templates/exchange/exchangeOrder.html
{% extends 'services/main-layout.html' %}
{% block Title %}Exchange Order{% endblock %}
{% block content%}
<div style="min-height:800px;background: #295AD9;" class='container'>
    <h1 class="text-center pt-3 text-light">Order</h1>
            {% for order in data%}
            <div class='orderExchange pb-5'>
                <div class="d-flex align-items-center mt-5 pb-3">
                    <a href={% url 'profile' slugFil=order.user %}>
                        <img class="hoverLinkExch" style="width: 80px; height: 80px; border-radius: 50%;" src={{ order.user.profile.Avatar.url}}>
                    </a>
                    <div class="ms-3">
                        <div class="h4">{{ order.title}}</div>
                        <div class="">{{ order.salary}}</div>
                    </div>
                </div> 
                <p class="techExchange">Technologies: <em class="">{{ order.technologies}}</em></p>
                <div class="py-3 px-5">{{ order.text}}</div>
                <div>
                    {% if user.is_authenticated%}
                        {% if request.user != order.user %}
                            <a href={% url 'massang' ToUser_name=order.user %}><button class="btnExchange text-uppercase my-2 px-5">Massange</button></a>
                        {% endif %}
                    {% else %}
                        <span class='PozorMess'>To Send massange you must <a href="#">login</a> in your account</span>
                    {% endif %}
                    <div class="d-flex  justify-content-between pt-2">
                        <div class="d-flex">
                            <div class="text-uppercase">{{ order.user}}</div>
                            <em class="ps-3" style="opacity: .7;">{{ order.user.profile.position}}</em>
                        </div>
                        <div class="text-uppercase"></div>
                        <div class="">{{ order.date}}</div>
                    </div>
                </div>
            </div>
            {% endfor%}
        </div>  
    </div>

</div>
{% endblock%}
{% block scripts%}  
<script>
</script>
{% endblock%}