CraftLayout/CraftLayout/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('services.urls')),
    path('', include('users.urls')),
    path('', include('exchange.urls')),
    path('', include('massanger.urls')),
]
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

CraftLayout/massanger/urls.py
from django.contrib import admin
from django.urls import path
from django.conf import settings
from .views import MassangPage
from django.conf.urls.static import static

urlpatterns = [
    path('massanger/<str:ToUser_name>', MassangPage, name='massang')
]

CraftLayout/users/urls.py
from telnetlib import LOGOUT
from django.contrib import admin
from django.urls import path
from django.conf import settings
from django.contrib.auth import views as authViews
from .views import profile, RegisterPage, AvatarPage, BannerPage, ChangeProfPage
urlpatterns = [
    path('changeBanner/', BannerPage, name="changeBanner"),
    path('changeProfile/', ChangeProfPage, name="changeProfile"),
    path('changeAvatar/', AvatarPage, name="changeAvatar"),
    path('reg/', RegisterPage, name='reg'),
    path('profile/<str:slugFil>', profile, name='profile'),
    path('login/', authViews.LoginView.as_view(template_name='users/login.html'), name='login'),
    path('exit/', authViews.LogoutView.as_view(template_name='users/exit.html'), name='exit')
]

CraftLayout/massanger/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils import timezone

class MassangerModel(models.Model):
    username = models.ForeignKey(User, verbose_name="Username", on_delete=models.CASCADE)
    Text = models.TextField(default=' ')
    SendTo = models.CharField(default='', max_length=255)
    date = models.DateTimeField(default=timezone.now)

    def __str__(self):
        return f'send from {self.username} to {self.SendTo}'

CraftLayout/massanger/forms.py
from dataclasses import field
from django import forms
from .models import MassangerModel

class massangerForm(forms.ModelForm):
    class Meta:
        model = MassangerModel
        fields = '__all__'

CraftLayout/massanger/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.models import User
from users.models import Profile
from .forms import massangerForm
from .models import MassangerModel

def MassangPage(request, ToUser_name):
    if request.user == 'AnonymousUser':
        return redirect('home')
    allUsers = User.objects.all()
    UserOrd = User.objects.filter(username=ToUser_name)
    NameProf = UserOrd[0]
    Name2 = ToUser_name
    sendTo = MassangerModel.objects.filter(username=request.user)
    sendToSend = []
    for i in sendTo:
        sendToSend.append(i.SendTo)

    sendToSendClear = [] 
    for item in sendToSend: 
        if item not in sendToSendClear: 
            sendToSendClear.append(item) 
    MassangerOrd = MassangerModel.objects.all()
    ProfileOrd = Profile.objects.filter(user=NameProf)
    YourName = request.user

    if ToUser_name == request.user:
        return redirect('massanger', ToUser_name == sendToSendClear[0])

    if request.method == "POST":
        form = massangerForm(request.POST)
        if form.is_valid():
            form.save()
    else:
        form = massangerForm()
    data = {
        'sendToSendClear': sendToSendClear,
        'sendTo': sendTo,
        'allUsers': allUsers,
        'Name2': Name2,
        'YourName': YourName,
        'form_mass': form,
        'UserOrd': UserOrd,
        'NameProf': NameProf,
        'ProfileOrd': ProfileOrd[0],
        'MassangerOrd': MassangerOrd
    }
    return render(request, 'massanger/massang.html', data)

CraftLayout/massanger/templates/massanger/massang.html
{% extends 'services/main-layout.html' %}
{% block Title %}Massanges{% endblock %}
{% block content%}
<div style="min-height: 640px;" class='container'>
    <div class="row">
        <div class="bg-light col-2">
            <div class="my-4">
                    {% for elem in sendToSendClear %}
                            <a href={% url 'massang' ToUser_name=elem %}><div style='background-color: #295AD9; border-radius: 10px;' class='p-3 text-white my-3'>{{ elem }}</div></a>
                    {% endfor %}
            </div>
        </div>
        <div class="col-10 p-0">
            <div style="background-color: #295AD9;height: 600px; overflow-y:scroll;" class="massagesInner pt-3">
                <div class="massagesSlider">
                    {% comment %} <div class="d-flex mb-4 bg-white ms-auto me-3 p-3" style="border-radius:10px;max-width: 680px">
                        <img src={{ ProfileOrd.Avatar.url}} style="width:50px;height: 50px;">
                        <div class="ps-3">
                            <div>{{ NameProf }}</div>
                            <div class="ps-3">{{ elem.Text}}</div> 
                            <div class="ms-3">{{ elem.date|date:"d M, H:i"}}</div>                           
                        </div>
                    </div> {% endcomment %}
                    {% for elem in MassangerOrd%}
                        {% if elem.SendTo %}
                            {% if elem.username == NameProf%}
                                <div class="d-flex mb-4 bg-white ms-3 p-3" style="border-radius:10px;max-width: 680px">
                                    <img src={{ ProfileOrd.Avatar.url}} style="border-radius: 50%;width:50px;height: 50px;">
                                    <div class="ps-3">
                                        <div>{{ NameProf }}</div>
                                        <div class="ps-3">{{ elem.Text}}</div> 
                                        <div class="ms-3">{{ elem.date|date:"d M, H:i"}}</div>                    
                                    </div>
                                </div> 
                            {% endif%}
                        {% endif %} 
                        {% if elem.username == request.user%}
                            {% if elem.SendTo == Name2%}
                                <div class="d-flex mb-4 bg-white ms-auto me-3 p-3" style="border-radius:10px;max-width: 680px">
                                    <div class="ps-3">
                                        <div>{{ elem.Text}}</div>
                                        <div class="ms-3">{{ elem.date|date:"d M, H:i"}}</div>                         
                                    </div>
                                </div> 
                            {% endif%}
                        {% endif %}              
                    {% endfor%}
                </div>
            </div>
            <div class="pt-3 px-3" style="min-height: 200px;">
                <form class="MassangerForm" method="post">
                    {% csrf_token %}
                    {{ form_mass.Text }}
                    <div class='d-none'>{{ form_mass.username }}</div>
                    <div class='d-none'>{{ form_mass.date }}</div>
                    <div class='d-none'>{{ form_mass.SendTo }}</div>
                    <button class="flare-button">send</button>
                </form>
            </div>
        </div>  
    </div>
</div>
{% endblock%}
{% block scripts%}  
<script>
    SelectInp = $('.MassangerForm select#id_username')
    selectsUser = $('.MassangerForm select#id_username option')
    selectSendTo = $('#id_SendTo')
    scroll = $('.massagesInner')
    window.onload = function() {
        scroll[0].scrollTop = '10000000000'; // Скролл первого элемента данного класса прокручиваем до нужного положения
    }
    for(let i = 0; i < selectsUser.length; i++){
        if (selectsUser[i].innerHTML == '{{ request.user }}'){
            SelectInp.val(selectsUser[i].value)
        }
    }
    selectSendTo.val('{{ Name2 }}')
</script>
{% endblock%}