CraftLayout/CraftLayout/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('services.urls')),
    path('', include('users.urls')),
    path('', include('exchange.urls')),
    path('', include('massanger.urls')),
]
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

CraftLayout/users/urls.py
from telnetlib import LOGOUT
from django.contrib import admin
from django.urls import path
from django.conf import settings
from django.contrib.auth import views as authViews
from .views import profile, RegisterPage, AvatarPage, BannerPage, ChangeProfPage
urlpatterns = [
    path('changeBanner/', BannerPage, name="changeBanner"),
    path('changeProfile/', ChangeProfPage, name="changeProfile"),
    path('changeAvatar/', AvatarPage, name="changeAvatar"),
    path('reg/', RegisterPage, name='reg'),
    path('profile/<str:slugFil>', profile, name='profile'),
    path('login/', authViews.LoginView.as_view(template_name='users/login.html'), name='login'),
    path('exit/', authViews.LogoutView.as_view(template_name='users/exit.html'), name='exit')
]

CraftLayout/users/models.py
from django.db import models
from django.contrib.auth.models import User
from PIL import Image

class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    Avatar = models.ImageField(default='default.png', upload_to='avatarks')
    banner = models.ImageField(default='default.png', upload_to='banners')
    position = models.CharField(default='Developer', max_length=150)

    def __str__(self):
        return f'Профайл пользователя {self.user.username}'

    def save(self, *args, **kwargs):
        super().save()

        image = Image.open(self.Avatar.path)

        if image.height > 256 or image.width > 256:
            resize = (256, 256)
            image.thumbnail(resize)
            image.save(self.Avatar.path)

CraftLayout/users/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm
from .models import Profile

class FormRegister(UserCreationForm):
    email = forms.EmailField(required=False)
    username = forms.CharField(required=False)

    class Meta:
        model = User
        fields = ['username', 'email', 'password1', 'password2']

class UserUpdateForm(forms.ModelForm):
    email = forms.EmailField(required=False)

    class Meta:
        model = User
        fields = ['email']

class FirstProfileform(forms.ModelForm):
    class Meta:
        model = Profile
        fields = ['position']
class SecondProfileform(forms.ModelForm):
    class Meta:
        model = User
        fields = ['email']

class ProfileImage(forms.ModelForm):
    def __init__(self, *args, **kwards):
        super(ProfileImage, self).__init__(*args, **kwards)
        self.fields['Avatar'].label = "Изображение профиля"

    class Meta:
        model = Profile
        fields = ['Avatar']

class ProfileBanner(forms.ModelForm):
    def __init__(self, *args, **kwards):
        super(ProfileBanner, self).__init__(*args, **kwards)
        self.fields['banner'].label = "Баннер профиля"

    class Meta:
        model = Profile
        fields = ['banner']

CraftLayout/users/views.py
from .models import Profile
from django.shortcuts import render, redirect
from .forms import ProfileImage, FormRegister, ProfileBanner, FirstProfileform, SecondProfileform
from exchange.models import Exchange
from django.contrib import messages
from django.contrib.auth import authenticate, login
from django.contrib.auth.models import User

def RegisterPage(request):
    if request.method == "POST":
        form = FormRegister(request.POST)
        if form.is_valid():
            form.save()
            username  = form.cleaned_data.get("username")
            password  = form.cleaned_data.get("password1")
            user = authenticate(request, username=username, password=password)
            login(request, user)
            return redirect('login')
    else:
        form = FormRegister()
    return render(request, 'users/reg.html', {'form':form})

def profile(request, slugFil):
    UserOrd = User.objects.filter(username=slugFil)
    NameProf = UserOrd[0]
    EmailProf = UserOrd[0].email
    ExchangeOrd = Exchange.objects.filter(user=NameProf)
    ProfileOrd = Profile.objects.filter(user=NameProf)
    ProfileOrd = ProfileOrd[0]
    data = {
        'EmailProf': EmailProf,
        'ExchangeOrd': ExchangeOrd,
        'UserOrd': UserOrd,
        'NameProf': NameProf,
        'ProfileOrd': ProfileOrd
    }
    return render(request, 'users/profile.html', data)

def AvatarPage(request):
    if request.method == "POST":
        img_profile = ProfileImage(request.POST, request.FILES, instance=request.user.profile)
        if img_profile.is_valid():
            img_profile.save()
            return redirect('home')
    else:
        img_profile = ProfileImage(instance=request.user.profile)
    return render(request, 'users/Avatar.html', {'img_profile': img_profile})

def BannerPage(request):
    if request.method == "POST":
        banner_profile = ProfileBanner(request.POST, request.FILES, instance=request.user.profile)
        if banner_profile.is_valid():
            banner_profile.save()
            return redirect('home')
    else:
        banner_profile = ProfileBanner(instance=request.user.profile)
    return render(request, 'users/Banner.html', {'banner_profile': banner_profile})

def ChangeProfPage(request):
    if request.method == "POST":
        First_form = FirstProfileform(request.POST, instance=request.user.profile)
        if First_form.is_valid():
            First_form.save()
            return redirect('home')
    else:
        First_form = FirstProfileform()

    if request.method == "POST":
        Second_form = SecondProfileform(request.POST, instance=request.user)
        if Second_form.is_valid():
            Second_form.save()
            return redirect('home')
    else:
        Second_form = SecondProfileform()

    data = {
        "First_form": First_form,
        "Second_form": Second_form
    } 
    return render(request, 'users/updateProfile.html', data)

CraftLayout/users/templates/users/Avatar.html
{% extends 'services/main-layout.html' %}
{% block Title %}Change Avatar{% endblock %}
{% block content%}
    <div style='height:800px;' class=' container d-flex justify-content-center align-items-center'>
        <form enctype="multipart/form-data" method="post">
            {% csrf_token %}
            {{ img_profile.Avatar }}
            <button class="btn my-2 flare-button">Save</button>            
        </form>
    </div>
{% endblock%}

{% block scripts%}  
{% comment %} <script>
    let labels = document.querySelectorAll('label')
    let inputs = document.querySelectorAll('input')
    for(var i = 1; i > inputs.length; i++){
        inputs[i].val() = ''
    }
    $('input').focus(function(){
        for(var elem in labels){
            if($(this).attr("id") == labels[elem].id){
                labels[elem].classList.add('ACTIVElab')
            }

        }
    });

    $('input').focusout(function(){
        for(var elem in labels){
            if($(this).attr("id") == labels[elem].id){
                labels[elem].classList.remove('ACTIVElab')
                if($(this).val() != ''){
                    labels[elem].classList.add('ACTIVElab')
                }
            }
        }
    });
</script> {% endcomment %}
{% endblock%}

CraftLayout/users/templates/users/Banner.html
{% extends 'services/main-layout.html' %}
{% block Title %}Change Banner{% endblock %}
{% block content%}
    <div style='height:800px;' class=' container d-flex justify-content-center align-items-center'>
        <form enctype="multipart/form-data" method="post">
            {% csrf_token %}
            {{ banner_profile.banner }}
            <button class="btn my-2 flare-button">Save</button>            
        </form>
    </div>
{% endblock%}

{% block scripts%}  
{% comment %} <script>
    let labels = document.querySelectorAll('label')
    let inputs = document.querySelectorAll('input')
    for(var i = 1; i > inputs.length; i++){
        inputs[i].val() = ''
    }
    $('input').focus(function(){
        for(var elem in labels){
            if($(this).attr("id") == labels[elem].id){
                labels[elem].classList.add('ACTIVElab')
            }

        }
    });

    $('input').focusout(function(){
        for(var elem in labels){
            if($(this).attr("id") == labels[elem].id){
                labels[elem].classList.remove('ACTIVElab')
                if($(this).val() != ''){
                    labels[elem].classList.add('ACTIVElab')
                }
            }
        }
    });
</script> {% endcomment %}
{% endblock%}

CraftLayout/users/templates/users/exit.html
{% extends 'services/main-layout.html' %}
{% block Title %}Exit{% endblock %}
{% block content%}
    <div style='height:800px;' class='container d-flex justify-content-center align-items-center'>
        <p class='bg-success text-light p-5' style='border-radius: 10px;'>Your loginout was conducted successfully!</p>
    </div>
{% endblock%}

CraftLayout/users/templates/users/login.html
{% extends 'services/main-layout.html' %}
{% block Title %}Login{% endblock %}
{% block content%}
    <div style='height:800px;' class='container d-flex justify-content-center align-items-center'>
        {% if not user.is_authenticated %}
        <form class="registerform" method="post">
            {% csrf_token %}
            <label id='id_username'>Username</label>
            {{ form.username }}</br>
            <label id='id_password'>Password</label>
            {{ form.password }}</br>
            {{ form.non_field_errors }} 
            <button class="btn my-2 flare-button">login</button><br>
            If you don't have account, you will <a href={% url 'reg'%}>register</a>
        </form>
        {% else %}
            <p class='bg-success p-5 text-light' style='border-radius: 10px;'>User is Logged</p>
        {% endif %}
    </div>
{% endblock%}

{% block scripts%}  
<script>
    let labels = document.querySelectorAll('label')
    let inputs = document.querySelectorAll('input')
    for(var i = 1; i > inputs.length; i++){
        inputs[i].val() = ''
    }
    $('input').focus(function(){
        for(var elem in labels){
            if($(this).attr("id") == labels[elem].id){
                labels[elem].classList.add('ACTIVElab')
            }

        }
    });

    $('input').focusout(function(){
        for(var elem in labels){
            if($(this).attr("id") == labels[elem].id){
                labels[elem].classList.remove('ACTIVElab')
                if($(this).val() != ''){
                    labels[elem].classList.add('ACTIVElab')
                }
            }
        }
    });
</script>
{% endblock%}

CraftLayout/users/templates/users/profile.html
{% extends 'services/main-layout.html' %}
{% load static %}
{% block Title %}Profile{% endblock %}
{% block content%}

{% if request.user == NameProf %}
<a href={% url 'changeBanner'%}>
    <div class="bannerInner  text-center" style="background-image: url({{ProfileOrd.banner.url}});">
        <img src={% static 'services/img/profile/add-banner.png'%} class="p-2" style="width: 350px;">
    </div>
</a> 
{% else%}
<div class="bannerInner1  text-center" style="background-image: url({{ProfileOrd.banner.url}});"></div>

{% endif%}
    <div style='min-height:800px; mb-3' class='container'>
        <div class="d-flex align-items-center">
            <div class='w-100 d-flex py-5 align-items-center'>
                
                {% if request.user == NameProf %}
                <a href={% url 'changeAvatar'%}>
                    <img src="{% static 'services/img/profile/add-photo.png' %}" class="addImgProfile" style="">
                    <img class="imgAvatarIcon" style="width: 80px; height: 80px; border-radius: 50%;" src={{ ProfileOrd.Avatar.url}}>
                </a>
                {% else%}
                <img class="imgAvatarIcon" style="width: 80px; height: 80px; border-radius: 50%;" src={{ ProfileOrd.Avatar.url}}>
                {% endif%}
                <div class="ps-4">
                    <div style="font-weight: 500; font-size: 24px;">
                        {{ NameProf }}
                        {% if request.user == NameProf %}
                            <a href={% url 'changeProfile' %}>
                                <img class="redactorProfile" style="width:18px;" src="{% static 'services/img/profile/pencil.png' %}" >
                            </a>
                        {% endif %}
                    </div>
                    <div class="text-secondary">{{ ProfileOrd.position}}</div>
                </div>
            </div>
            <div>
                {% if user.is_authenticated%}
                    {% if request.user != NameProf%}
                        <a href={% url 'massang' ToUser_name=NameProf %}><button class="btn px-5 my-0 flare-button h-100">Massage</button></a>
                    {% else%}
                        <div style="font-weight: 500; font-size: 24px;">Contacts</div>
                    {% endif %}
                {% else %}
                <div class="PozorMess">To send massange you need <a href="reg">register</a> or <a href="login">login</a></div>
                {% endif%}
                <div class="text-secondary">{{EmailProf}}</div>
            </div>

        </div>
        <h2 class="mb-5 text-center" style="color: #295AD9">Orders</h2>
        {% for order in ExchangeOrd%}
            <div class='orderExchange mt-4 p-4 text-light'>
                <div class="d-flex justify-content-between">
                    <div>
                        <div class="h5">{{ order.title}}</div>
                        <div class="h3">{{ order.salary}}</div>
                    </div> 
                </div>
                <div class="">{{ order.text|truncatechars:250}}</div>
                <a href={% url 'exchange'%}{{ order.id }}><button class="btnExchange text-uppercase my-2 px-5">See more</button></a>
                <div class="d-flex justify-content-between pt-2">
                    <div class="text-uppercase">{{ order.user}}</div>
                    <div class="text-uppercase"></div>
                    <div class="">{{ order.date}}</div>
                </div>
            </div>
        {% endfor%}
        {% if request.user == NameProf %}
            <a href={% url 'createOrder'%}><button class="btn px-5 my-4 flare-button h-100">new exchange</button></a>
        {% endif %}
    </div>
{% endblock%}
{% block scripts%}  
<script>
    let labels = document.querySelectorAll('label')
    let inputs = document.querySelectorAll('input')

    $('input').focus(function(){
        for(var elem in labels){
            if($(this).attr("id") == labels[elem].id){
                labels[elem].classList.add('ACTIVElab')
            }
            
        }
    });

    $('input').focusout(function(){
        for(var elem in labels){
            if($(this).attr("id") == labels[elem].id){
                labels[elem].classList.remove('ACTIVElab')
                if($(this).val() != ''){
                    labels[elem].classList.add('ACTIVElab')
                }
            }
        }
    });
</script>
{% endblock%}

CraftLayout/users/templates/users/reg.html
{% extends 'services/main-layout.html' %}
{% block Title %}Register{% endblock %}

{% block content%}
    <div style='height:800px;' class='container d-flex justify-content-center align-items-center'>
        {% if not user.is_authenticated %}
        <form class="registerform" method="post">
            {% csrf_token %}
            <label id='id_username'>Username</label>
            {{ form.username }}</br>
            

            <label id='id_email'>Email</label>
            {{ form.email }}</br>
            <label id='id_password1'>Password</label>
            {{ form.password1 }}</br>
            <label id='id_password2'>Repeat Password</label>
            {{ form.password2 }}</br>
            {{ form.errors }}{{ form.non_field_errors }}       
            <button class="btn my-2 flare-button">Register</button>
            <div>if you are registered, you can <a href={% url 'login'%}>login</a></div>
        </form>
        
        {% else %}
            <p class='bg-success p-5 text-light' style='border-radius: 10px;'>User is Logged</p>
        {% endif %}
    </div>
{% endblock%}

{% block scripts%}  
<script>
    let labels = document.querySelectorAll('label')
    let inputs = document.querySelectorAll('input')

    window.onload = function() {
        for(var i = 1; i > inputs.length; i++){
            inputs[i].val() = ''
        }
    }
    $('input').focus(function(){
        for(var elem in labels){
            if($(this).attr("id") == labels[elem].id){
                labels[elem].classList.add('ACTIVElab')
            }

        }
    });

    $('input').focusout(function(){
        for(var elem in labels){
            if($(this).attr("id") == labels[elem].id){
                labels[elem].classList.remove('ACTIVElab')
                if($(this).val() != ''){
                    labels[elem].classList.add('ACTIVElab')
                }
            }
        }
    });
</script>
{% endblock%}

CraftLayout/users/templates/users/updateProfile.html
{% extends 'services/main-layout.html' %}
{% block Title %}Update Profile{% endblock %}
{% block content%}
    <div style='height:800px;' class='container d-flex justify-content-center align-items-center'>
        <div class="w-50">
            <form class="registerform ProfileUpdateForm" style="width: 100%;" enctype="multipart/form-data" method="post">
                {% csrf_token %}
                <label id='id_position'>Position</label>
                {{ First_form.position }}
                <button class="btn my-2 flare-button">Save position</button>            
            </form>
            <form class="registerform ProfileUpdateForm my-3" style="width: 100%;"  enctype="multipart/form-data" method="post">
                {% csrf_token %}
                <label id='id_email'>Email</label>
                {{ Second_form.email }}
                <button class="btn my-2 flare-button">Save Email</button>            
            </form>
        </div>
    </div>
{% endblock%}

{% block scripts%}  
<script>
    let labels = document.querySelectorAll('label')
    let inputs = document.querySelectorAll('input')
    $('input').focus(function(){
        for(var elem in labels){
            if($(this).attr("id") == labels[elem].id){
                labels[elem].classList.add('ACTIVElab')
            }

        }
    });
    $('input').focusout(function(){
        for(var elem in labels){
            if($(this).attr("id") == labels[elem].id){
                labels[elem].classList.remove('ACTIVElab')
                if($(this).val() != ''){
                    labels[elem].classList.add('ACTIVElab')
                }
            }
        }
    });

    inputs[1].value = ''
</script>
{% endblock%}